name: v$(VersionPart_Major).$(VersionPart_Minor).$(VersionPart_Build)

variables:
- name: VersionPart_Major
  value: '1'
- name: VersionPart_Minor
  value: '1'
- name: VersionPart_Build
  value: '$[counter(format(''{0}.{1}'', variables[''VersionPart_Major''], variables[''VersionPart_Minor'']), 0)]'
- name: Build_Version
  value: $(VersionPart_Major).$(VersionPart_Minor).$(VersionPart_Build).0

resources:
  repositories:
  - repository: templates
    type: git
    name: Eos.Nav.Platform/BuildTemplates

trigger:
  branches:
    include: [ 'master' ]

stages:
- stage: Build
  jobs:
  - template: 'dotNet/jobs/build-and-test.yml@templates'
    parameters:
      dotNetVersion: 6.x
- stage: Deploy
  dependsOn: Build
  jobs:
  - template: 'dotNet/jobs/deploy-nuget.yml@templates'
    parameters:
      dotNetVersion: 6.x